import type { Card } from "./types";

export const CARDS: Card[] = [
  // LEADERS
  {
    id: "ldr-iron",
    name: "Generale Ferro",
    type: "leader",
    cost: 180,
    hp: 220,
    attack: 28,
    defense: 14,
    speed: 0.7,
    range: 1,
    ability: "rally",
    abilityDesc: "Aumenta del 25% il danno delle truppe alleate vicine.",
    score: 95,
    description: "Veterano di mille battaglie, ispira i suoi uomini.",
    emoji: "🎖️",
  },
  {
    id: "ldr-falco",
    name: "Comandante Falco",
    type: "leader",
    cost: 160,
    hp: 170,
    attack: 22,
    defense: 10,
    speed: 1.1,
    range: 2,
    ability: "scout",
    abilityDesc: "Rivela un'area più ampia (fog of war).",
    score: 88,
    description: "Stratega della ricognizione aerea.",
    emoji: "🦅",
  },
  // SOLDIERS
  {
    id: "sld-fanteria",
    name: "Fanteria",
    type: "soldier",
    cost: 40,
    hp: 80,
    attack: 12,
    defense: 6,
    speed: 0.9,
    range: 1,
    score: 35,
    description: "Truppa base, affidabile in campo aperto.",
    emoji: "🪖",
    prefersBiome: "plain",
  },
  {
    id: "sld-ranger",
    name: "Ranger",
    type: "soldier",
    cost: 70,
    hp: 65,
    attack: 16,
    defense: 4,
    speed: 1.2,
    range: 3,
    ability: "ambush",
    abilityDesc: "Bonus +50% danno se in foresta.",
    score: 55,
    description: "Tiratore scelto specializzato in imboscate.",
    emoji: "🏹",
    prefersBiome: "forest",
  },
  {
    id: "sld-alpino",
    name: "Alpino",
    type: "soldier",
    cost: 60,
    hp: 95,
    attack: 11,
    defense: 10,
    speed: 0.8,
    range: 1,
    ability: "fortify",
    abilityDesc: "+50% difesa in montagna.",
    score: 50,
    description: "Resistente al freddo e al fuoco nemico.",
    emoji: "🧗",
    prefersBiome: "mountain",
  },
  {
    id: "sld-genio",
    name: "Genio d'assalto",
    type: "soldier",
    cost: 90,
    hp: 110,
    attack: 18,
    defense: 8,
    speed: 0.8,
    range: 1,
    score: 65,
    description: "Truppa d'élite per le linee del fronte.",
    emoji: "⚔️",
  },
  // VEHICLES
  {
    id: "vhc-tank",
    name: "Carro Pesante",
    type: "vehicle",
    cost: 150,
    hp: 200,
    attack: 26,
    defense: 18,
    speed: 0.6,
    range: 2,
    score: 90,
    description: "Corazza spessa, fuoco devastante.",
    emoji: "🛡️",
    prefersBiome: "plain",
  },
  {
    id: "vhc-jeep",
    name: "Jeep da ricognizione",
    type: "vehicle",
    cost: 80,
    hp: 70,
    attack: 10,
    defense: 4,
    speed: 1.6,
    range: 1,
    ability: "blitz",
    abilityDesc: "Velocità elevata per flanking rapido.",
    score: 50,
    description: "Veloce e leggera, ideale per fianchi nemici.",
    emoji: "🚙",
  },
  {
    id: "vhc-aereo",
    name: "Caccia",
    type: "vehicle",
    cost: 170,
    hp: 90,
    attack: 24,
    defense: 6,
    speed: 1.8,
    range: 4,
    ability: "bombard",
    abilityDesc: "Attacco a lungo raggio dall'alto.",
    score: 92,
    description: "Supremazia aerea sul campo di battaglia.",
    emoji: "✈️",
  },
  {
    id: "vhc-nave",
    name: "Cannoniera",
    type: "vehicle",
    cost: 140,
    hp: 160,
    attack: 22,
    defense: 12,
    speed: 0.9,
    range: 4,
    ability: "bombard",
    abilityDesc: "Domina i mari, fuoco a lungo raggio.",
    score: 85,
    description: "Dominio navale, devastante a distanza.",
    emoji: "🚢",
    prefersBiome: "sea",
  },
];

export const CARD_BY_ID = (id: string) => CARDS.find((c) => c.id === id)!;
